# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Crtuvn <- function(l, u) {
    .Call(`_mcmcsae_Crtuvn`, l, u)
}

Crtmvn_Gibbs_dense <- function(v, Ut, ustar, eps) {
    .Call(`_mcmcsae_Crtmvn_Gibbs_dense`, v, Ut, ustar, eps)
}

Crtmvn_Gibbs_sparse <- function(v, Ut, ustar, eps) {
    .Call(`_mcmcsae_Crtmvn_Gibbs_sparse`, v, Ut, ustar, eps)
}

Crtmvn_slice_Gibbs_dense <- function(v, Ut, ustar, eps) {
    .Call(`_mcmcsae_Crtmvn_slice_Gibbs_dense`, v, Ut, ustar, eps)
}

Crtmvn_slice_Gibbs_sparse <- function(v, Ut, ustar, eps) {
    .Call(`_mcmcsae_Crtmvn_slice_Gibbs_sparse`, v, Ut, ustar, eps)
}

CrTNprobit <- function(mu, y) {
    .Call(`_mcmcsae_CrTNprobit`, mu, y)
}

TMVN_HMC_C <- function(S, S_cols, v0, x0, s_adj, refl_fac, zero_mu, mu, simplified, VS, diagnostic, bounces, t_sim, max_refl) {
    .Call(`_mcmcsae_TMVN_HMC_C`, S, S_cols, v0, x0, s_adj, refl_fac, zero_mu, mu, simplified, VS, diagnostic, bounces, t_sim, max_refl)
}

cCHM_dsC_Cholesky <- function(a, perm, super, Imult, m, LDL) {
    .Call(`_mcmcsae_cCHM_dsC_Cholesky`, a, perm, super, Imult, m, LDL)
}

cCHMf_solve <- function(a, b, system) {
    .Call(`_mcmcsae_cCHMf_solve`, a, b, system)
}

cCHMf_solve_matrix <- function(a, b, system) {
    .Call(`_mcmcsae_cCHMf_solve_matrix`, a, b, system)
}

cCHMf_spsolve <- function(a, b, system) {
    .Call(`_mcmcsae_cCHMf_spsolve`, a, b, system)
}

cCHM_update_inplace <- function(object, parent, mult) {
    .Call(`_mcmcsae_cCHM_update_inplace`, object, parent, mult)
}

CrPGapprox <- function(n, b, z, m) {
    .Call(`_mcmcsae_CrPGapprox`, n, b, z, m)
}

Crnorm <- function(n, mean = 0, sd = 1) {
    .Call(`_mcmcsae_Crnorm`, n, mean, sd)
}

Crgig <- function(n, p, a, b) {
    .Call(`_mcmcsae_Crgig`, n, p, a, b)
}

CrCRT <- function(y, r, m = 20L) {
    .Call(`_mcmcsae_CrCRT`, y, r, m)
}

copy_vector <- function(x) {
    .Call(`_mcmcsae_copy_vector`, x)
}

v_update <- function(y, plus, x) {
    invisible(.Call(`_mcmcsae_v_update`, y, plus, x))
}

mv_update <- function(y, plus, M, x) {
    invisible(.Call(`_mcmcsae_mv_update`, y, plus, M, x))
}

inverseSPD <- function(M) {
    .Call(`_mcmcsae_inverseSPD`, M)
}

Ccholesky <- function(M) {
    .Call(`_mcmcsae_Ccholesky`, M)
}

Cbacksolve <- function(M, y) {
    .Call(`_mcmcsae_Cbacksolve`, M, y)
}

Cforwardsolve <- function(M, y) {
    .Call(`_mcmcsae_Cforwardsolve`, M, y)
}

CbacksolveM <- function(M, y) {
    .Call(`_mcmcsae_CbacksolveM`, M, y)
}

CforwardsolveM <- function(M, y) {
    .Call(`_mcmcsae_CforwardsolveM`, M, y)
}

dotprodC <- function(x, y) {
    .Call(`_mcmcsae_dotprodC`, x, y)
}

fast_aggrC <- function(x, group, n) {
    .Call(`_mcmcsae_fast_aggrC`, x, group, n)
}

Csparse_numeric_prod <- function(A, y) {
    .Call(`_mcmcsae_Csparse_numeric_prod`, A, y)
}

CsparseS_numeric_prod <- function(A, y) {
    .Call(`_mcmcsae_CsparseS_numeric_prod`, A, y)
}

Cdense_numeric_prod <- function(A, y) {
    .Call(`_mcmcsae_Cdense_numeric_prod`, A, y)
}

Cdense_numeric_crossprod <- function(A, y) {
    .Call(`_mcmcsae_Cdense_numeric_crossprod`, A, y)
}

Csparse_numeric_crossprod <- function(A, y) {
    .Call(`_mcmcsae_Csparse_numeric_crossprod`, A, y)
}

Cdense_dense_prod <- function(A, B) {
    .Call(`_mcmcsae_Cdense_dense_prod`, A, B)
}

Csparse_dense_prod <- function(A, y) {
    .Call(`_mcmcsae_Csparse_dense_prod`, A, y)
}

Cdense_sparse_prod <- function(A, B) {
    .Call(`_mcmcsae_Cdense_sparse_prod`, A, B)
}

CsparseS_dense_prod <- function(A, y) {
    .Call(`_mcmcsae_CsparseS_dense_prod`, A, y)
}

Cdense_sparseS_prod <- function(M, Q) {
    .Call(`_mcmcsae_Cdense_sparseS_prod`, M, Q)
}

Cdense_diag_prod <- function(M, d) {
    .Call(`_mcmcsae_Cdense_diag_prod`, M, d)
}

Cdense_dense_crossprod <- function(A, B) {
    .Call(`_mcmcsae_Cdense_dense_crossprod`, A, B)
}

Csparse_dense_crossprod <- function(A, B) {
    .Call(`_mcmcsae_Csparse_dense_crossprod`, A, B)
}

Cdense_sparse_crossprod <- function(A, B) {
    .Call(`_mcmcsae_Cdense_sparse_crossprod`, A, B)
}

Cdense_diag_crossprod <- function(M, d) {
    .Call(`_mcmcsae_Cdense_diag_crossprod`, M, d)
}

Cdense_sparse_tcrossprod <- function(y, A) {
    .Call(`_mcmcsae_Cdense_sparse_tcrossprod`, y, A)
}

Cdiag_sparse_prod <- function(x, A) {
    .Call(`_mcmcsae_Cdiag_sparse_prod`, x, A)
}

sparse_sum_x <- function(n, ind1, ind2, M1x, M2x, UD1, UD2, w1, w2) {
    .Call(`_mcmcsae_sparse_sum_x`, n, ind1, ind2, M1x, M2x, UD1, UD2, w1, w2)
}

diagC <- function(A) {
    .Call(`_mcmcsae_diagC`, A)
}

add_diagC <- function(A, d) {
    .Call(`_mcmcsae_add_diagC`, A, d)
}

Cdense_crossprod_sym0 <- function(M) {
    .Call(`_mcmcsae_Cdense_crossprod_sym0`, M)
}

Cdense_crossprod_sym <- function(M, q) {
    .Call(`_mcmcsae_Cdense_crossprod_sym`, M, q)
}

Csparse_sym_twist <- function(Q, p) {
    .Call(`_mcmcsae_Csparse_sym_twist`, Q, p)
}

Cdense_crossprod_sym2 <- function(A, B) {
    .Call(`_mcmcsae_Cdense_crossprod_sym2`, A, B)
}

CdiagU <- function(n) {
    .Call(`_mcmcsae_CdiagU`, n)
}

Cdiag <- function(x) {
    .Call(`_mcmcsae_Cdiag`, x)
}

Cscale_dense <- function(A, d) {
    .Call(`_mcmcsae_Cscale_dense`, A, d)
}

Cscale_sparse <- function(A, d) {
    .Call(`_mcmcsae_Cscale_sparse`, A, d)
}

Csparse_dense_crossprod_sym <- function(A, Q) {
    .Call(`_mcmcsae_Csparse_dense_crossprod_sym`, A, Q)
}

Csparse_crossprod_sym <- function(A, Q) {
    .Call(`_mcmcsae_Csparse_crossprod_sym`, A, Q)
}

Csparse_diag_crossprod_sym <- function(A, Q) {
    .Call(`_mcmcsae_Csparse_diag_crossprod_sym`, A, Q)
}

Csparse_crossprod_sym2 <- function(A, B) {
    .Call(`_mcmcsae_Csparse_crossprod_sym2`, A, B)
}

prec2se_cor <- function(Q) {
    .Call(`_mcmcsae_prec2se_cor`, Q)
}

log1pexpC <- function(x) {
    .Call(`_mcmcsae_log1pexpC`, x)
}

Cdense_kron <- function(M1, M2) {
    .Call(`_mcmcsae_Cdense_kron`, M1, M2)
}

Crepgen <- function(v, n, M2) {
    .Call(`_mcmcsae_Crepgen`, v, n, M2)
}

Cnnz_per_col_scps_template <- function(X, j1_ind, j2_ind) {
    .Call(`_mcmcsae_Cnnz_per_col_scps_template`, X, j1_ind, j2_ind)
}

Ccreate_sparse_crossprod_sym_template <- function(X, j1_ind, j2_ind, nnz_per_col) {
    .Call(`_mcmcsae_Ccreate_sparse_crossprod_sym_template`, X, j1_ind, j2_ind, nnz_per_col)
}

Ctab <- function(Dim, reduced, perm, num, x) {
    .Call(`_mcmcsae_Ctab`, Dim, reduced, perm, num, x)
}

Ctab_numeric_prod <- function(A, y, ignore_x = FALSE) {
    .Call(`_mcmcsae_Ctab_numeric_prod`, A, y, ignore_x)
}

Ctab_dense_prod <- function(A, y) {
    .Call(`_mcmcsae_Ctab_dense_prod`, A, y)
}

Cdense_tab_tcrossprod <- function(y, A) {
    .Call(`_mcmcsae_Cdense_tab_tcrossprod`, y, A)
}

Ctab_numeric_crossprod <- function(A, y) {
    .Call(`_mcmcsae_Ctab_numeric_crossprod`, A, y)
}

Ctab_dense_crossprod <- function(A, y) {
    .Call(`_mcmcsae_Ctab_dense_crossprod`, A, y)
}

Ctab_unary_crossprod <- function(A) {
    .Call(`_mcmcsae_Ctab_unary_crossprod`, A)
}

Ctab2dgC <- function(M) {
    .Call(`_mcmcsae_Ctab2dgC`, M)
}

Ctab2mat <- function(M) {
    .Call(`_mcmcsae_Ctab2mat`, M)
}

